name: Delete merged branch
on:
  pull_request:
    types: [closed]
jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && !contains(fromJSON('["master", "main"]'), github.event.pull_request.head.ref)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
